site_name: Compose UI Architecture
theme:
  name: material
  logo: assets/icon.svg
  custom_dir: overrides
  palette: 
    scheme: default
    primary: white
    accent: green
  font:
    text: "Roboto"
    code: "JetBrains Mono"
  features:
    - navigation.tabs
    - content.code.annotate
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences    
extra:
  analytics:
    provider: firebase
    property: "compose-ui-arch"
nav:
  - "Home": index.md
  - state.md
  - actions.md
  - screen.md
  - coordinator.md  
  
